### ISSUE TITLE
Allocation of land for present USD owners

### ISSUE THREAD

**Issue by enadorange** [BEAR-finance/bearland#1]
1) Request to have fair allocation of a predetermined amount of land ( as decided by team ) to be available for sale for those who own USD and would like to participate. Land will be given to the proportion of USD you are willing to give up. Thus negating need for an auction for this specific/early phase.

OR

2) Allow first buyers of land to pick from prime real estate spots

**Comment by Specbee-onchain** [comment]
Not gonna happen until initial launch
