### ISSUE TITLE
Auction didnt happen 20 days ago

### ISSUE THREAD

**Issue by diegoxt24** [BEAR-finance/bearland#3]
The price of the token USD just got changed from 1 BNB= 378 (USD, not real USD, it is just the name assigned), to 1 BNB= 600 USD in an arbitrary way based on personal needs of the group. The first investors suffered all the loss from it. We have been requesting a money back guarantee wich is getting denied and denied. I request the help of the staff or even Github moderators to help us solve the situation with this project. We are concerned people wich are victims and money taken from us in an unfair way and now they refuse to give it back. We demand we receive our money back.

**Comment by Specbee-onchain** [comment]
Impressive, I am not handling customer support issues. I will pass your issue
