### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by Specbee-onchain** [BEAR-finance/bearland#4]
Integration for all of the contracts required on the forked UI. Auction contracts are not needed at all.

**Comment by MimsOua** [comment]
thanks for the news 👌👍

**Comment by Specbee-onchain** [comment]
Link for the working marketplace should be posted by me shortly

**Comment by Specbee-onchain** [comment]
I re-forked everything using the existing smart contracts deployed from dev wallet. Link for the marketplace, most of the stuff that is being worked on is configuration https://github.com/BEAR-finance/marketplace-legacy

**Comment by Specbee-onchain** [comment]
Legacy marketplace is deprecated. New one will be up today
