### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Specbee-onchain** [BEAR-finance/bearland#5]
WIP
- [x] Launch LAND contracts

- [x] Launch Marketplace

- [ ] Launch Builder

- [ ] Launch virtual world

**Comment by Specbee-onchain** [comment]
<img width="1126" alt="Screenshot 2021-04-13 at 01 04 16" src="https://user-images.githubusercontent.com/82381305/114468441-2cbf6b80-9bf4-11eb-8da2-b79711b3d4a0.png">

**Comment by MimsOua** [comment]
launch build?  what do you mean ?

**Comment by MimsOua** [comment]
launch build?  what do you mean ?

**Comment by Specbee-onchain** [comment]
mainnet is on
